### ISSUE TITLE
Stuck in the tutorial

### ISSUE THREAD

**Issue by McPhelpsius** [joeeames/AngularFundamentalsFiles#26]
I've been trying to get past the Thrid Module, but the code isn't working for me when I try to request an event from the data file. Could you point me to some help?

**Comment by kdamken** [comment]
I'm having the same issue, it's preventing me from moving forward in the course. @joeeames Do you have any advice?

Here is my error log:
Error: ENOENT: no such file or directory, open 'app/data/event1.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at eventGrabber.get (/Users/user_name/Desktop/DemoApp/scripts/web-server.js:14:20)
    at Layer.handle [as handle_request](/Users/user_name/Desktop/DemoApp/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/user_name/Desktop/DemoApp/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/user_name/Desktop/DemoApp/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request](/Users/user_name/Desktop/DemoApp/node_modules/express/lib/router/layer.js:95:5)
    at /Users/user_name/Desktop/DemoApp/node_modules/express/lib/router/index.js:277:22
    at param (/Users/user_name/Desktop/DemoApp/node_modules/express/lib/router/index.js:349:14)

**Comment by joeeames** [comment]
Did you review the course discussion forum for similar issues and solutions?

**Comment by kdamken** [comment]
Hey thanks for responding. I didn't even realize that board existed lol. Turns out it was due to me missing a slash on my file path.

For other users, the link to the discussion board is - https://app.pluralsight.com/library/courses/angularjs-fundamentals/discussion
